---

- name: Disable clamd in 4GB Servers
  hosts: <host_group>
  gather_facts: true

  tasks:

  - name: Get Memory
    debug: 
      msg: "Memory less than 4GB; Proceeding to Disable CLAMD"
    when: ansible_memtotal_mb < 4097
 
  - name: Creating clamddisable file
    file:
      path: /etc/clamddisable
      state: touch
      mode: u=rw,g=r,o=r
    when: ansible_memtotal_mb < 4097

  - name: Restarting Exim Service
    service:
      name: exim
      state: restarted
    when: ansible_memtotal_mb < 4097
